/*
* @Class : GlobalConstantClass
* @Author : Narayana(573339).
* @Description : Class to declare all constants variables.
* @Change History :
*/
public class GlobalConstantClass {
        //General Constants
        public static final String UTF8 = 'UTF-8';                  
        public static final String STRINGSUCCESSCODE201 = '201';
        public static final String STRINGSTATUSCODE0 = '0';
        public static final String STRINGSTATUSCODE404 = '404';       
        public static final String PLEASEPROVIDEBODYSTRUCTURE = 'Please provide body structure'; 
        public static final String INTEGRATION = 'Integration'; 
        public static final String BADDATA = '400';        
        public static final Integer SUCCESSCODE201 = 201;
        public static final Integer SUCCESSCODE200 = 200;
        public static final Integer FAILURECODE = 500;      
       
}